### ISSUE TITLE
Repository lacks a license

### ISSUE THREAD

**Issue by eap** [ikester/blender-docker#3]
Please license this repository, right now the copyright status is unclear. Can I suggest Apache 2, MIT, or 2-clause BSD, all of which are fairly permissive licenses with liability protections?

Adding a license will enable some people to make pull requests.

**Comment by ikester** [comment]
Hi @e4p. Absolutely. I simply didn't imagine that people would find this useful enough to consider submitting PRs. I'll license it using MIT.

**Comment by ikester** [comment]
Resolved with PR #4
