### ISSUE TITLE
Why not just install from apt?

### ISSUE THREAD

**Issue by golyalpha** [ikester/blender-docker#7]
This is more to feed my curiosity than anything, but Blender's apt repo is part of the base Ubuntu distribution you're using.  
Why build it yourself if you can just `apt-get install blender` it?

I imagine it would save a lot of work, but maybe it's not an ideal way of doing things that way...?

**Comment by ikester** [comment]
Because the apt repos don't usually support the latest and greatest versions of Blender. This way the Docker image can be updated to the newest version independently. It also pulls in fewer dependencies, making the image somewhat smaller.

**Comment by golyalpha** [comment]
It's obvious this particular issue has not aged well, as at the time of posting, the latest stable release *was* on apt repositories. :)

**Comment by ikester** [comment]
Yes :). I know that was a couple of years ago but, just curious, do you use Blender in Docker?

**Comment by golyalpha** [comment]
Not at the moment, no, mostly because I don't have hardware to run BinD on right now.
I did originally. 

Currently trying to figure out Kubernetes+GPU and Kubernetes itself, once I do, I may get back to using Blender inside Docker.
